/* AppObjects.h - Generated by Visual Multi-Thread Win32 */

#ifndef APPOBJECTS_H
#define APPOBJECTS_H

#define _WIN32_WINNT 0x501
#include <windows.h>

extern HANDLE Cliente;
extern SOCKET ClientSocket;

#endif /* APPOBJECTS_H */

